{
  "formatVersion": "1.1",
  "component": {
    "group": "com.luoyunmin.plugin1",
    "module": "timeplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "timeplugin-1.0.0.jar",
          "url": "timeplugin-1.0.0.jar",
          "size": 9149,
          "sha512": "5d3cf1aa83f36a1f3921869c1ed9912eabe0b5a1de5f70218c461643658ff73fbdde8ae00a98852d5f80c1a04103932f6d5a2e0f4ef32c4850a6adc1875da82a",
          "sha256": "d8f73cdd58d04d41babeba645be3bd596493f986eb12229ba3a6ae8c4d6ccc4e",
          "sha1": "ca3b8895a0c2c79c1ba4e86dbefb0f5cb008bace",
          "md5": "49fc6f3df881a2e98215afa2df70514c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "timeplugin-1.0.0.jar",
          "url": "timeplugin-1.0.0.jar",
          "size": 9149,
          "sha512": "5d3cf1aa83f36a1f3921869c1ed9912eabe0b5a1de5f70218c461643658ff73fbdde8ae00a98852d5f80c1a04103932f6d5a2e0f4ef32c4850a6adc1875da82a",
          "sha256": "d8f73cdd58d04d41babeba645be3bd596493f986eb12229ba3a6ae8c4d6ccc4e",
          "sha1": "ca3b8895a0c2c79c1ba4e86dbefb0f5cb008bace",
          "md5": "49fc6f3df881a2e98215afa2df70514c"
        }
      ]
    }
  ]
}
